- Handling warnings

In [1]:
import warnings
warnings.filterwarnings("ignore")

- Loading modules

In [2]:
import pandas as pd

- Read cortisol dataset

In [3]:
df_cortisol = pd.read_csv("../raw_data/cortisol/raw_data_measures.csv")
df_cortisol

   Sample  Cortisol (pg/mL) Attachment
0      38              4.21     Secure
1      16              3.59     Secure
2      32             22.75     Secure
3       1              5.62   Insecure
4       7              1.83   Insecure
5      39              3.07   Insecure
6       5              2.28     Secure
7      63              7.08   Insecure
8      27              2.26     Secure
9      23              4.76     Secure

In [4]:
df_cortisol.shape

(10, 3)

- Read processed IgA dataset

In [5]:
df_processed_data = pd.read_csv("../processed_data/1_processed_data_IgA.csv")
df_processed_data.head(5)

,ID,Gender,IgA_Average_Morning,IgA_Average_Afternoon,Average_Difference,Attachment
0,1,Male,21.765240,28.368055,6.602815,Insecure
1,4,Male,28.473065,50.881961,22.408896,Secure
2,5,Female,161.424693,46.867951,-114.556742,Secure
3,7,Female,24.173487,35.942378,14.343241,Insecure
4,11,Male,78.013279,382.715268,345.590046,Unknown

- Making merge and deleting NaN values

In [6]:
df_merge = df_cortisol.merge(right=df_processed_data, left_on="Sample", right_on="ID", how="left")
df_merge

,Sample,Cortisol (pg/mL),Attachment_x,ID,Gender,IgA_Average_Morning,IgA_Average_Afternoon,Average_Difference,Attachment_y
0,38,4.21,Secure,NaN,NaN,NaN,NaN,NaN,NaN
1,16,3.59,Secure,16.0,Female,57.476955,73.891936,16.414980,Secure
2,32,22.75,Secure,32.0,Male,32.565326,44.611069,12.045743,Secure
3,1,5.62,Insecure,1.0,Male,21.765240,28.368055,6.602815,Insecure
4,7,1.83,Insecure,7.0,Female,24.173487,35.942378,14.343241,Insecure
5,39,3.07,Insecure,NaN,NaN,NaN,NaN,NaN,NaN
6,5,2.28,Secure,5.0,Female,161.424693,46.867951,-114.556742,Secure
7,63,7.08,Insecure,63.0,Male,26.219626,20.066422,-6.153204,Insecure
8,27,2.26,Secure,27.0,Female,43.637360,37.759187,-15.388331,Secure
9,23,4.76,Secure,23.0,Female,80.824884,47.632842,-33.192041,Secure

In [24]:
df_merge = df_merge.dropna()
df_merge

,Sample,Cortisol (pg/mL),Attachment_x,ID,Gender,IgA_Average_Morning,IgA_Average_Afternoon,Average_Difference,Attachment_y
1,16,3.59,Secure,16.0,Female,57.476955,73.891936,16.414980,Secure
2,32,22.75,Secure,32.0,Male,32.565326,44.611069,12.045743,Secure
3,1,5.62,Insecure,1.0,Male,21.765240,28.368055,6.602815,Insecure
4,7,1.83,Insecure,7.0,Female,24.173487,35.942378,14.343241,Insecure
6,5,2.28,Secure,5.0,Female,161.424693,46.867951,-114.556742,Secure
7,63,7.08,Insecure,63.0,Male,26.219626,20.066422,-6.153204,Insecure
8,27,2.26,Secure,27.0,Female,43.637360,37.759187,-15.388331,Secure
9,23,4.76,Secure,23.0,Female,80.824884,47.632842,-33.192041,Secure

- Processing merge dataset

In [25]:
df_merge.columns

Index(['Sample', 'Cortisol (pg/mL)', 'Attachment_x', 'ID', 'Gender',
       'IgA_Average_Morning', 'IgA_Average_Afternoon', 'Average_Difference',
       'Attachment_y'],
      dtype='object')

In [26]:
df_merge = df_merge[['ID', 'Gender', 'IgA_Average_Morning', 
                    'IgA_Average_Afternoon', 'Average_Difference', 
                    'Cortisol (pg/mL)', 'Attachment_y']]
df_merge.columns = ['ID', 'Gender', 'IgA_Average_Morning', 
                    'IgA_Average_Afternoon', 'Average_Difference', 
                    'Cortisol (pg/mL)', 'Attachment']
df_merge

,ID,Gender,IgA_Average_Morning,IgA_Average_Afternoon,Average_Difference,Cortisol (pg/mL),Attachment
1,16.0,Female,57.476955,73.891936,16.414980,3.59,Secure
2,32.0,Male,32.565326,44.611069,12.045743,22.75,Secure
3,1.0,Male,21.765240,28.368055,6.602815,5.62,Insecure
4,7.0,Female,24.173487,35.942378,14.343241,1.83,Insecure
6,5.0,Female,161.424693,46.867951,-114.556742,2.28,Secure
7,63.0,Male,26.219626,20.066422,-6.153204,7.08,Insecure
8,27.0,Female,43.637360,37.759187,-15.388331,2.26,Secure
9,23.0,Female,80.824884,47.632842,-33.192041,4.76,Secure

- Checking some statistics

In [27]:
df_merge[["Cortisol (pg/mL)", "Attachment"]].groupby(by=["Attachment"]).mean()

            Cortisol (pg/mL)
Attachment
Insecure            4.843333
Secure              7.128000

In [28]:
df_merge[["Cortisol (pg/mL)", "Attachment"]].groupby(by=["Attachment"]).median()

            Cortisol (pg/mL)
Attachment
Insecure                5.62
Secure                  3.59

- Exporting processed dataset

In [29]:
df_merge.to_csv("../processed_data/2_processed_data_cortisol.csv", index=False)