- Handling warnings

In [13]:
import warnings
warnings.filterwarnings("ignore")

- Loading modules

In [14]:
import pandas as pd

- Read cortisol dataset

In [15]:
df_cortisol = pd.read_csv("../raw_data/cortisol/raw_data_measures.csv")
df_cortisol.sort_values(by="Sample")

   Sample  Cortisol (pg/mL) Attachment
3       1              5.62   Insecure
6       5              2.28     Secure
4       7              1.83   Insecure
1      16              3.59     Secure
9      23              4.76     Secure
8      27              2.26     Secure
2      32             22.75     Secure
0      38              4.21     Secure
5      39              3.07   Insecure
7      63              7.08   Insecure

In [16]:
df_cortisol.shape

(10, 3)

- Read processed IgA dataset

In [17]:
df_processed_data = pd.read_csv("../processed_data/1_processed_data_IgA.csv")
df_processed_data.head(5)

,ID,Gender,sIgA_Average_Morning,sIgA_Average_Afternoon,sIgA_Average_Difference,sIgA_Average_Morning_log,sIgA_Average_Afternoon_log,sIgA_Average_Difference_log,Attachment
0,1,Male,21.765240,28.368055,6.602815,3.077296,3.338237,0.260941,Insecure
1,4,Male,28.473065,50.881961,22.408896,3.348951,3.687484,0.338533,Secure
2,5,Female,161.424693,46.867951,-114.556742,5.084039,3.847334,-1.236705,Secure
3,7,Female,24.173487,35.942378,14.343241,3.179553,3.581917,0.402364,Insecure
4,11,Male,78.013279,382.715268,345.590046,4.196295,5.947291,1.750996,Unknown

- Making merge and deleting NaN values

In [18]:
df_merge = df_cortisol.merge(right=df_processed_data, left_on="Sample", right_on="ID", how="left")
df_merge

,Sample,Cortisol (pg/mL),Attachment_x,ID,Gender,sIgA_Average_Morning,sIgA_Average_Afternoon,sIgA_Average_Difference,sIgA_Average_Morning_log,sIgA_Average_Afternoon_log,sIgA_Average_Difference_log,Attachment_y
0,38,4.21,Secure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,16,3.59,Secure,16.0,Female,57.476955,73.891936,16.414980,3.974519,4.178677,0.204158,Secure
2,32,22.75,Secure,32.0,Male,32.565326,44.611069,12.045743,3.417520,3.749981,0.332461,Secure
3,1,5.62,Insecure,1.0,Male,21.765240,28.368055,6.602815,3.077296,3.338237,0.260941,Insecure
4,7,1.83,Insecure,7.0,Female,24.173487,35.942378,14.343241,3.179553,3.581917,0.402364,Insecure
5,39,3.07,Insecure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,5,2.28,Secure,5.0,Female,161.424693,46.867951,-114.556742,5.084039,3.847334,-1.236705,Secure
7,63,7.08,Insecure,63.0,Male,26.219626,20.066422,-6.153204,3.262951,2.995264,-0.267687,Insecure
8,27,2.26,Secure,27.0,Female,43.637360,37.759187,-15.388331,3.751583,3.631229,-0.120354,Secure
9,23,4.76,Secure,23.0,Female,80.824884,47.632842,-33.192041,4.392023,3.846883,-0.545141,Secure

In [19]:
df_merge = df_merge.dropna()
df_merge

,Sample,Cortisol (pg/mL),Attachment_x,ID,Gender,sIgA_Average_Morning,sIgA_Average_Afternoon,sIgA_Average_Difference,sIgA_Average_Morning_log,sIgA_Average_Afternoon_log,sIgA_Average_Difference_log,Attachment_y
1,16,3.59,Secure,16.0,Female,57.476955,73.891936,16.414980,3.974519,4.178677,0.204158,Secure
2,32,22.75,Secure,32.0,Male,32.565326,44.611069,12.045743,3.417520,3.749981,0.332461,Secure
3,1,5.62,Insecure,1.0,Male,21.765240,28.368055,6.602815,3.077296,3.338237,0.260941,Insecure
4,7,1.83,Insecure,7.0,Female,24.173487,35.942378,14.343241,3.179553,3.581917,0.402364,Insecure
6,5,2.28,Secure,5.0,Female,161.424693,46.867951,-114.556742,5.084039,3.847334,-1.236705,Secure
7,63,7.08,Insecure,63.0,Male,26.219626,20.066422,-6.153204,3.262951,2.995264,-0.267687,Insecure
8,27,2.26,Secure,27.0,Female,43.637360,37.759187,-15.388331,3.751583,3.631229,-0.120354,Secure
9,23,4.76,Secure,23.0,Female,80.824884,47.632842,-33.192041,4.392023,3.846883,-0.545141,Secure

- Processing merge dataset

In [20]:
df_merge.columns

Index(['Sample', 'Cortisol (pg/mL)', 'Attachment_x', 'ID', 'Gender',
       'sIgA_Average_Morning', 'sIgA_Average_Afternoon',
       'sIgA_Average_Difference', 'sIgA_Average_Morning_log',
       'sIgA_Average_Afternoon_log', 'sIgA_Average_Difference_log',
       'Attachment_y'],
      dtype='object')

In [21]:
df_merge = df_merge[['ID', 'Cortisol (pg/mL)', 'Gender',
       'sIgA_Average_Morning', 'sIgA_Average_Afternoon',
       'sIgA_Average_Difference', 'sIgA_Average_Morning_log',
       'sIgA_Average_Afternoon_log', 'sIgA_Average_Difference_log',
       'Attachment_y']]
df_merge.columns = ['ID', 'Cortisol (pg/mL)', 'Gender',
       'sIgA_Average_Morning', 'sIgA_Average_Afternoon',
       'sIgA_Average_Difference', 'sIgA_Average_Morning_log',
       'sIgA_Average_Afternoon_log', 'sIgA_Average_Difference_log',
       'Attachment']
df_merge

,ID,Cortisol (pg/mL),Gender,sIgA_Average_Morning,sIgA_Average_Afternoon,sIgA_Average_Difference,sIgA_Average_Morning_log,sIgA_Average_Afternoon_log,sIgA_Average_Difference_log,Attachment
1,16.0,3.59,Female,57.476955,73.891936,16.414980,3.974519,4.178677,0.204158,Secure
2,32.0,22.75,Male,32.565326,44.611069,12.045743,3.417520,3.749981,0.332461,Secure
3,1.0,5.62,Male,21.765240,28.368055,6.602815,3.077296,3.338237,0.260941,Insecure
4,7.0,1.83,Female,24.173487,35.942378,14.343241,3.179553,3.581917,0.402364,Insecure
6,5.0,2.28,Female,161.424693,46.867951,-114.556742,5.084039,3.847334,-1.236705,Secure
7,63.0,7.08,Male,26.219626,20.066422,-6.153204,3.262951,2.995264,-0.267687,Insecure
8,27.0,2.26,Female,43.637360,37.759187,-15.388331,3.751583,3.631229,-0.120354,Secure
9,23.0,4.76,Female,80.824884,47.632842,-33.192041,4.392023,3.846883,-0.545141,Secure

- Checking some statistics

In [22]:
df_merge[["Cortisol (pg/mL)", "Attachment"]].groupby(by=["Attachment"]).mean()

            Cortisol (pg/mL)
Attachment
Insecure            4.843333
Secure              7.128000

In [23]:
df_merge[["Cortisol (pg/mL)", "Attachment"]].groupby(by=["Attachment"]).median()

            Cortisol (pg/mL)
Attachment
Insecure                5.62
Secure                  3.59

- Exporting processed dataset

In [24]:
df_merge.to_csv("../processed_data/4_processed_data_cortisol.csv", index=False)